name: emotionfood
favicon: null
layout_spectrum: 0.97673
typography_spectrum: 0.99929
title: 'Food, Restaurant, Chefs and Magazine Photography'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fef7dc'
    - '#fdcb2e'
    - '#765453'
    - '#fc8b25'
    - '#272402'
  brandStrength: 0
  lightness: 0.9375
  saturation: 1
  rhythmicContrast: 0
purpose: []
