name: emotionfood
favicon: null
layout_spectrum: 0.99929
typography_spectrum: 0.99929
title: 'Food, Restaurant, Chefs and Magazine Photography'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#b57957'
    - '#633c30'
    - '#fdd263'
    - '#66a16f'
  brandStrength: 0.11218163766898215
  lightness: 0.7202483357395977
  saturation: 0.07476704637520015
  rhythmicContrast: 0.15888638817705214
purpose: []
