name: emotionfood
favicon: null
layout_spectrum: 0.75952
typography_spectrum: 0.99929
title: 'Food, Restaurant, Chefs and Magazine Photography'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#dcb9aa'
    - '#3d2321'
    - '#de7b30'
    - '#8f6858'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
