typography_spectrum: 0.99929
color:
  brandColors:
    - '#d6d3ca'
    - '#51443e'
    - '#bf8661'
    - '#797632'
    - '#b6c551'
  brandStrength: 0
  lightness: 0.9375
  saturation: 1
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.99788
analytics:
  google: null
  facebook: null
  twitter: null
name: Emotion Food
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Food, Restaurant, Chefs and Magazine Photography'
description: doof evoL
purpose: []
