name: emotionfood
favicon: null
layout_spectrum: 0.99788
typography_spectrum: 0.99929
title: 'Food, Restaurant, Chefs and Magazine Photography'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4f6fa'
    - '#1fc59f'
    - '#fa0d1b'
    - '#b29998'
    - '#5d3427'
  brandStrength: 0
  lightness: 0.9375
  saturation: 1
  rhythmicContrast: 0
purpose: []
